name: Trigger Segment-TensorRT Workflow

on:
  push:
    branches:
      - main  # Kích hoạt khi có commit vào main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Segment-TensorRT Repository
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          --data '{"event_type": "trigger-tensorrt"}' \
          https://api.github.com/repos/LTNhoTin/Segment-TensorRT/dispatches
